security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/api/(login|games|game|setups|register|createupdategame)
            stateless: true
            security: false
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/setups, roles: PUBLIC_ACCESS }
        - { path: ^/api/games, roles: PUBLIC_ACCESS }
        - { path: ^/api/game, roles: PUBLIC_ACCESS }
        - { path: ^/api/createupdategame, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }