<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/get_ServiceLocator_XM_0Nc2Service.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/get_ServiceLocator_INktMs_Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/get_ServiceLocator_XM_0Nc2Service.php
class get_ServiceLocator_XM_0Nc2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xM.0Nc2' shared service.
========
class get_ServiceLocator_INktMs_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.INktMs.' shared service.
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/get_ServiceLocator_INktMs_Service.php
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiSetupController::index' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\ApiSetupController::index()', 'getApiSetupControllerindexService', true],
            'App\\Controller\\ApiSetupController::create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiSetupController::create()', 'getApiSetupControllercreateService', true],
            'App\\Controller\\ApiSetupController::show' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\ApiSetupController::show()', 'getApiSetupControllershowService', true],
            'App\\Controller\\ApiSetupController::edit' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()', 'getApiSetupControllereditService', true],
            'App\\Controller\\ApiSetupController::delete' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::delete()', 'getApiSetupControllerdeleteService', true],
            'App\\Controller\\GameController::index' => ['privates', '.service_locator.FH3MMyQ.App\\Controller\\GameController::index()', 'getGameControllerindexService', true],
            'App\\Controller\\GameController::game' => ['privates', '.service_locator.nZ_4Tsq.App\\Controller\\GameController::game()', 'getGameControllergameService', true],
            'App\\Controller\\GameController::createupdate' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameController::createupdate()', 'getGameControllercreateupdateService', true],
            'App\\Controller\\GameController::JeuDelete' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()', 'getGameControllerJeuDeleteService', true],
            'App\\Controller\\GameControllerApi::index' => ['privates', '.service_locator.FH3MMyQ.App\\Controller\\GameControllerApi::index()', 'getGameControllerApiindexService', true],
            'App\\Controller\\GameControllerApi::game' => ['privates', '.service_locator.nZ_4Tsq.App\\Controller\\GameControllerApi::game()', 'getGameControllerApigameService', true],
            'App\\Controller\\GameControllerApi::createupdate' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameControllerApi::createupdate()', 'getGameControllerApicreateupdateService', true],
            'App\\Controller\\GameControllerApi::JeuDelete' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameControllerApi::JeuDelete()', 'getGameControllerApiJeuDeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SetupController::index' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\SetupController::index()', 'getSetupControllerindexService', true],
            'App\\Controller\\SetupController::create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\SetupController::create()', 'getSetupControllercreateService', true],
            'App\\Controller\\SetupController::show' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\SetupController::show()', 'getSetupControllershowService', true],
            'App\\Controller\\SetupController::delete' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\SetupController::delete()', 'getSetupControllerdeleteService', true],
            'App\\Controller\\SetupController::edit' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()', 'getSetupControllereditService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController::create' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\UserController::create()', 'getUserControllercreateService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserControllerApi::index' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserControllerApi::index()', 'getUserControllerApiindexService', true],
            'App\\Controller\\UserControllerApi::register' => ['privates', '.service_locator.ISmgmTD.App\\Controller\\UserControllerApi::register()', 'getUserControllerApiregisterService', true],
            'App\\Controller\\UserControllerApi::create' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()', 'getUserControllerApicreateService', true],
            'App\\Controller\\UserControllerApi::show' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserControllerApi::show()', 'getUserControllerApishowService', true],
            'App\\Controller\\UserControllerApi::edit' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::edit()', 'getUserControllerApieditService', true],
            'App\\Controller\\UserControllerApi::delete' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()', 'getUserControllerApideleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiSetupController:index' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\ApiSetupController::index()', 'getApiSetupControllerindexService', true],
            'App\\Controller\\ApiSetupController:create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiSetupController::create()', 'getApiSetupControllercreateService', true],
            'App\\Controller\\ApiSetupController:show' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\ApiSetupController::show()', 'getApiSetupControllershowService', true],
            'App\\Controller\\ApiSetupController:edit' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()', 'getApiSetupControllereditService', true],
            'App\\Controller\\ApiSetupController:delete' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::delete()', 'getApiSetupControllerdeleteService', true],
            'App\\Controller\\GameController:index' => ['privates', '.service_locator.FH3MMyQ.App\\Controller\\GameController::index()', 'getGameControllerindexService', true],
            'App\\Controller\\GameController:game' => ['privates', '.service_locator.nZ_4Tsq.App\\Controller\\GameController::game()', 'getGameControllergameService', true],
            'App\\Controller\\GameController:createupdate' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameController::createupdate()', 'getGameControllercreateupdateService', true],
            'App\\Controller\\GameController:JeuDelete' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()', 'getGameControllerJeuDeleteService', true],
            'App\\Controller\\GameControllerApi:index' => ['privates', '.service_locator.FH3MMyQ.App\\Controller\\GameControllerApi::index()', 'getGameControllerApiindexService', true],
            'App\\Controller\\GameControllerApi:game' => ['privates', '.service_locator.nZ_4Tsq.App\\Controller\\GameControllerApi::game()', 'getGameControllerApigameService', true],
            'App\\Controller\\GameControllerApi:createupdate' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameControllerApi::createupdate()', 'getGameControllerApicreateupdateService', true],
            'App\\Controller\\GameControllerApi:JeuDelete' => ['privates', '.service_locator.rYJauon.App\\Controller\\GameControllerApi::JeuDelete()', 'getGameControllerApiJeuDeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\SetupController:index' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\SetupController::index()', 'getSetupControllerindexService', true],
            'App\\Controller\\SetupController:create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\SetupController::create()', 'getSetupControllercreateService', true],
            'App\\Controller\\SetupController:show' => ['privates', '.service_locator.JtLqJUl.App\\Controller\\SetupController::show()', 'getSetupControllershowService', true],
            'App\\Controller\\SetupController:delete' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\SetupController::delete()', 'getSetupControllerdeleteService', true],
            'App\\Controller\\SetupController:edit' => ['privates', '.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()', 'getSetupControllereditService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\UserController:create' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\UserController::create()', 'getUserControllercreateService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserController::show()', 'getUserControllershowService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserController::delete()', 'getUserControllerdeleteService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Controller\\UserControllerApi:index' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserControllerApi::index()', 'getUserControllerApiindexService', true],
            'App\\Controller\\UserControllerApi:register' => ['privates', '.service_locator.ISmgmTD.App\\Controller\\UserControllerApi::register()', 'getUserControllerApiregisterService', true],
            'App\\Controller\\UserControllerApi:create' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()', 'getUserControllerApicreateService', true],
            'App\\Controller\\UserControllerApi:show' => ['privates', '.service_locator.lURhuIT.App\\Controller\\UserControllerApi::show()', 'getUserControllerApishowService', true],
            'App\\Controller\\UserControllerApi:edit' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::edit()', 'getUserControllerApieditService', true],
            'App\\Controller\\UserControllerApi:delete' => ['privates', '.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()', 'getUserControllerApideleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiSetupController::index' => '?',
            'App\\Controller\\ApiSetupController::create' => '?',
            'App\\Controller\\ApiSetupController::show' => '?',
            'App\\Controller\\ApiSetupController::edit' => '?',
            'App\\Controller\\ApiSetupController::delete' => '?',
            'App\\Controller\\GameController::index' => '?',
            'App\\Controller\\GameController::game' => '?',
            'App\\Controller\\GameController::createupdate' => '?',
            'App\\Controller\\GameController::JeuDelete' => '?',
            'App\\Controller\\GameControllerApi::index' => '?',
            'App\\Controller\\GameControllerApi::game' => '?',
            'App\\Controller\\GameControllerApi::createupdate' => '?',
            'App\\Controller\\GameControllerApi::JeuDelete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SetupController::index' => '?',
            'App\\Controller\\SetupController::create' => '?',
            'App\\Controller\\SetupController::show' => '?',
            'App\\Controller\\SetupController::delete' => '?',
            'App\\Controller\\SetupController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::create' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserControllerApi::index' => '?',
            'App\\Controller\\UserControllerApi::register' => '?',
            'App\\Controller\\UserControllerApi::create' => '?',
            'App\\Controller\\UserControllerApi::show' => '?',
            'App\\Controller\\UserControllerApi::edit' => '?',
            'App\\Controller\\UserControllerApi::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiSetupController:index' => '?',
            'App\\Controller\\ApiSetupController:create' => '?',
            'App\\Controller\\ApiSetupController:show' => '?',
            'App\\Controller\\ApiSetupController:edit' => '?',
            'App\\Controller\\ApiSetupController:delete' => '?',
            'App\\Controller\\GameController:index' => '?',
            'App\\Controller\\GameController:game' => '?',
            'App\\Controller\\GameController:createupdate' => '?',
            'App\\Controller\\GameController:JeuDelete' => '?',
            'App\\Controller\\GameControllerApi:index' => '?',
            'App\\Controller\\GameControllerApi:game' => '?',
            'App\\Controller\\GameControllerApi:createupdate' => '?',
            'App\\Controller\\GameControllerApi:JeuDelete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SetupController:index' => '?',
            'App\\Controller\\SetupController:create' => '?',
            'App\\Controller\\SetupController:show' => '?',
            'App\\Controller\\SetupController:delete' => '?',
            'App\\Controller\\SetupController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:create' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserControllerApi:index' => '?',
            'App\\Controller\\UserControllerApi:register' => '?',
            'App\\Controller\\UserControllerApi:create' => '?',
            'App\\Controller\\UserControllerApi:show' => '?',
            'App\\Controller\\UserControllerApi:edit' => '?',
            'App\\Controller\\UserControllerApi:delete' => '?',
        ]);

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/get_ServiceLocator_XM_0Nc2Service.php
        if (isset($container->privates['.service_locator.xM.0Nc2'])) {
            return $container->privates['.service_locator.xM.0Nc2'];
        }

        return $container->privates['.service_locator.xM.0Nc2'] = $instance;
========
        if (isset($container->privates['.service_locator.INktMs.'])) {
            return $container->privates['.service_locator.INktMs.'];
        }

        return $container->privates['.service_locator.INktMs.'] = $instance;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/get_ServiceLocator_INktMs_Service.php
    }
}
