<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/get_Lazy_DataCollector_DumpService.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/get_Lazy_DataCollector_DumpService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Lazy_DataCollector_DumpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.lazy.data_collector.dump' shared service.
     *
     * @return \Symfony\Component\HttpKernel\DataCollector\DumpDataCollector
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['.lazy.data_collector.dump'] = new \ReflectionClass('Symfony\Component\HttpKernel\DataCollector\DumpDataCollector')->newLazyProxy(static fn () => self::do($container, false));
        }

        return ($container->services['data_collector.dump'] ?? self::getDataCollector_DumpService($container));
    }
}
