<?php

namespace ContainerN8Szkh2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiSetupControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fnXt8rG.App\Controller\ApiSetupController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.fnXt8rG'] ?? $container->load('get_ServiceLocator_FnXt8rGService'));

        if (isset($container->privates['.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()'])) {
            return $container->privates['.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\ApiSetupController::edit()', $container);

        if (isset($container->privates['.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()'])) {
            return $container->privates['.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()'];
        }

        return $container->privates['.service_locator.fnXt8rG.App\\Controller\\ApiSetupController::edit()'] = $instance;
    }
}
