<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/getGameControllergameService.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/getGameControllergameService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllergameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nZ_4Tsq.App\Controller\GameController::game()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nZ_4Tsq.App\\Controller\\GameController::game()'] = ($container->privates['.service_locator.nZ_4Tsq'] ?? $container->load('get_ServiceLocator_NZ4TsqService'))->withContext('App\\Controller\\GameController::game()', $container);
    }
}
