<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/getGameControllerJeuDeleteService.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/getGameControllerJeuDeleteService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllerJeuDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYJauon.App\Controller\GameController::JeuDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.rYJauon'] ?? $container->load('get_ServiceLocator_RYJauonService'));

        if (isset($container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'])) {
            return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'];
        }

        $instance = $a->withContext('App\\Controller\\GameController::JeuDelete()', $container);

        if (isset($container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'])) {
            return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'];
        }

        return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'] = $instance;
    }
}
