<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/getGameControllerApiindexService.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/getGameControllerApiindexService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllerApiindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FH3MMyQ.App\Controller\GameControllerApi::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FH3MMyQ.App\\Controller\\GameControllerApi::index()'] = ($container->privates['.service_locator.FH3MMyQ'] ?? $container->load('get_ServiceLocator_FH3MMyQService'))->withContext('App\\Controller\\GameControllerApi::index()', $container);
    }
}
