<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/getUserControllerApideleteService.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/getUserControllerApideleteService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerApideleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3p1IsKM.App\Controller\UserControllerApi::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.3p1IsKM'] ?? $container->load('get_ServiceLocator_3p1IsKMService'));

        if (isset($container->privates['.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()'])) {
            return $container->privates['.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\UserControllerApi::delete()', $container);

        if (isset($container->privates['.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()'])) {
            return $container->privates['.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()'];
        }

        return $container->privates['.service_locator.3p1IsKM.App\\Controller\\UserControllerApi::delete()'] = $instance;
    }
}
