<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerHL6bcjw/getUserControllerApiindexService.php
namespace ContainerHL6bcjw;
========
namespace ContainerN8Szkh2;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/ContainerN8Szkh2/getUserControllerApiindexService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerApiindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lURhuIT.App\Controller\UserControllerApi::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lURhuIT.App\\Controller\\UserControllerApi::index()'] = ($container->privates['.service_locator.lURhuIT'] ?? $container->load('get_ServiceLocator_LURhuITService'))->withContext('App\\Controller\\UserControllerApi::index()', $container);
    }
}
