<?php

namespace ContainerG2rC1E3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lURhuIT.App\Controller\UserController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lURhuIT.App\\Controller\\UserController::index()'] = ($container->privates['.service_locator.lURhuIT'] ?? $container->load('get_ServiceLocator_LURhuITService'))->withContext('App\\Controller\\UserController::index()', $container);
    }
}
