<?php

namespace ContainerX2RlPkH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllerJeuDeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYJauon.App\Controller\GameController::JeuDelete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.rYJauon'] ?? $container->load('get_ServiceLocator_RYJauonService'));

        if (isset($container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'])) {
            return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'];
        }

        $instance = $a->withContext('App\\Controller\\GameController::JeuDelete()', $container);

        if (isset($container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'])) {
            return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'];
        }

        return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::JeuDelete()'] = $instance;
    }
}
