<?php

namespace ContainerX2RlPkH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerApiregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ISmgmTD.App\Controller\UserControllerApi::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'hasher' => '?',
            'repo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\UserControllerApi::register()', $container);

        if (isset($container->privates['.service_locator.ISmgmTD.App\\Controller\\UserControllerApi::register()'])) {
            return $container->privates['.service_locator.ISmgmTD.App\\Controller\\UserControllerApi::register()'];
        }

        return $container->privates['.service_locator.ISmgmTD.App\\Controller\\UserControllerApi::register()'] = $instance;
    }
}
