<?php

namespace ContainerS5NuNUy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SetupFormType' shared autowired service.
     *
     * @return \App\Form\SetupFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SetupFormType.php';

        return $container->privates['App\\Form\\SetupFormType'] = new \App\Form\SetupFormType();
    }
}
