<?php

namespace ContainerEoI32ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3p1IsKMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3p1IsKM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\UserRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.3p1IsKM'])) {
            return $container->privates['.service_locator.3p1IsKM'];
        }

        return $container->privates['.service_locator.3p1IsKM'] = $instance;
    }
}
