<?php

namespace ContainerEoI32ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RYJauonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYJauon' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'jeuRepository' => ['privates', 'App\\Repository\\GameRepository', 'getGameRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'jeuRepository' => 'App\\Repository\\GameRepository',
            'manager' => '?',
        ]);

        if (isset($container->privates['.service_locator.rYJauon'])) {
            return $container->privates['.service_locator.rYJauon'];
        }

        return $container->privates['.service_locator.rYJauon'] = $instance;
    }
}
