<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG2rC1E3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG2rC1E3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG2rC1E3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG2rC1E3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG2rC1E3\App_KernelDevDebugContainer([
    'container.build_hash' => 'G2rC1E3',
    'container.build_id' => 'a0fcb9f7',
    'container.build_time' => 1778578400,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG2rC1E3');
