<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5NuNUy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5NuNUy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5NuNUy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5NuNUy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5NuNUy\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5NuNUy',
    'container.build_id' => '4e70ec29',
    'container.build_time' => 1778667674,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5NuNUy');
