<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEoI32ae\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEoI32ae/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEoI32ae.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEoI32ae\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEoI32ae\App_KernelDevDebugContainer([
    'container.build_hash' => 'EoI32ae',
    'container.build_id' => '42536dff',
    'container.build_time' => 1778609621,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEoI32ae');
