<?php

namespace ContainerA7kbeag;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerApicreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O6aUYCb.App\Controller\UserControllerApi::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.O6aUYCb'] ?? $container->load('get_ServiceLocator_O6aUYCbService'));

        if (isset($container->privates['.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()'])) {
            return $container->privates['.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()'];
        }

        $instance = $a->withContext('App\\Controller\\UserControllerApi::create()', $container);

        if (isset($container->privates['.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()'])) {
            return $container->privates['.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()'];
        }

        return $container->privates['.service_locator.O6aUYCb.App\\Controller\\UserControllerApi::create()'] = $instance;
    }
}
