<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/get_ServiceLocator_FnXt8rGService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/get_ServiceLocator_FnXt8rGService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FnXt8rGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fnXt8rG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\SetupRepository', 'getSetupRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'repo' => 'App\\Repository\\SetupRepository',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.fnXt8rG'])) {
            return $container->privates['.service_locator.fnXt8rG'];
        }

        return $container->privates['.service_locator.fnXt8rG'] = $instance;
    }
}
