<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/get_Messenger_SigningSerializer_SigningKeyService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/get_Messenger_SigningSerializer_SigningKeyService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_SigningSerializer_SigningKeyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.signing_serializer.signing_key' shared service.
     *
     * @return \string
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.signing_serializer.signing_key'] = $container->getParameter('kernel.secret');
    }
}
