<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/get_LazyProfilerService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/get_LazyProfilerService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_LazyProfilerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.lazy_profiler' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Profiler\Profiler
     */
    public static function do($container, $lazyLoad = true)
    {
        if (true === $lazyLoad) {
            return $container->privates['.lazy_profiler'] = new \ReflectionClass('Symfony\Component\HttpKernel\Profiler\Profiler')->newLazyProxy(static fn () => self::do($container, false));
        }

        return ($container->services['.container.private.profiler'] ?? self::get_Container_Private_ProfilerService($container));
    }
}
