<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/get_ServiceLocator_NW8xGL3Service.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/get_ServiceLocator_NW8xGL3Service.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NW8xGL3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NW8xGL3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NW8xGL3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.login' => ['privates', 'debug.security.event_dispatcher.login', 'getDebug_Security_EventDispatcher_LoginService', true],
            'security.event_dispatcher.api' => ['privates', 'debug.security.event_dispatcher.api', 'getDebug_Security_EventDispatcher_ApiService', true],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.login' => '?',
            'security.event_dispatcher.api' => '?',
        ]);
    }
}
