<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/getGameControllerindexService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/getGameControllerindexService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FH3MMyQ.App\Controller\GameController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FH3MMyQ.App\\Controller\\GameController::index()'] = ($container->privates['.service_locator.FH3MMyQ'] ?? $container->load('get_ServiceLocator_FH3MMyQService'))->withContext('App\\Controller\\GameController::index()', $container);
    }
}
