<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/getGameControllercreateupdateService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/getGameControllercreateupdateService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameControllercreateupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rYJauon.App\Controller\GameController::createupdate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.rYJauon'] ?? $container->load('get_ServiceLocator_RYJauonService'));

        if (isset($container->privates['.service_locator.rYJauon.App\\Controller\\GameController::createupdate()'])) {
            return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::createupdate()'];
        }

        $instance = $a->withContext('App\\Controller\\GameController::createupdate()', $container);

        if (isset($container->privates['.service_locator.rYJauon.App\\Controller\\GameController::createupdate()'])) {
            return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::createupdate()'];
        }

        return $container->privates['.service_locator.rYJauon.App\\Controller\\GameController::createupdate()'] = $instance;
    }
}
