<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/getLoaderInterfaceService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/getLoaderInterfaceService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoaderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1vYpZ1B.Symfony\Component\Config\Loader\LoaderInterface' shared service.
     *
     * @return \Symfony\Component\Config\Loader\LoaderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1vYpZ1B": it needs an instance of "Symfony\\Component\\Config\\Loader\\LoaderInterface" but this type has been excluded from autowiring.');
    }
}
