<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/getSetupControllereditService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/getSetupControllereditService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fnXt8rG.App\Controller\SetupController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.fnXt8rG'] ?? $container->load('get_ServiceLocator_FnXt8rGService'));

        if (isset($container->privates['.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()'])) {
            return $container->privates['.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\SetupController::edit()', $container);

        if (isset($container->privates['.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()'])) {
            return $container->privates['.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()'];
        }

        return $container->privates['.service_locator.fnXt8rG.App\\Controller\\SetupController::edit()'] = $instance;
    }
}
