<?php

<<<<<<<< HEAD:back/var/cache/dev/ContainerX2RlPkH/getUserControllerindexService.php
namespace ContainerX2RlPkH;
========
namespace Container8kAvUxa;
>>>>>>>> 106b221696bf2a1f81345fdf9a0ade453a0274e2:back/var/cache/dev/Container8kAvUxa/getUserControllerindexService.php


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lURhuIT.App\Controller\UserController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lURhuIT.App\\Controller\\UserController::index()'] = ($container->privates['.service_locator.lURhuIT'] ?? $container->load('get_ServiceLocator_LURhuITService'))->withContext('App\\Controller\\UserController::index()', $container);
    }
}
